version: "3.7"

services:
  web:
    build: .
    container_name: django-gunicorn
    restart: always
    env_file:
      - .env
    expose:
      - 8000
    command:
      "python3 manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:1.17
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./app/static:/etc/nginx/static
    depends_on:
      - web